# Generated by Django 2.1.3 on 2018-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
